networks:
  kind:
    external: true
services:
  terminal:
    build:
      context: terminal
      args:
        CONTAINER_USER: terminal
    environment:
      GLOBAL_CONTAINER_IMAGE_REGISTRY: ${GLOBAL_CONTAINER_IMAGE_REGISTRY:-}
      KUBE_CLUSTER_SERVER_MAP: ${KUBE_CLUSTER_SERVER_MAP:-}
      KUBE_CONTEXT_LOCAL_DEVELOP: ${KUBE_CONTEXT_LOCAL_DEVELOP:-}
      KUBE_CONTEXT_LOCAL_STAGING: ${KUBE_CONTEXT_LOCAL_STAGING:-}
    networks:
      - kind
    volumes:
      - ${HOST_AWS_PATH:-~/.aws}:/opt/.aws:ro
      - ${HOST_KUBE_CONFIG_PATH:-~/.kube/config}:/opt/.kube/config:ro
      - ${HOST_WORKSPACE_DIR_PATH:-.}:/home/terminal/workspace:rw
      - cache:/home/telminal/.cache:rw
    working_dir: /home/terminal/workspace
volumes:
  cache: {}
